apiVersion: v1
kind: Pod
metadata:
  name: alpine-sleeper
  namespace: alpine-demo
  labels:
    app: alpine-sleeper
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      resources:
        requests:
          cpu: "10m"
          memory: "16Mi"
        limits:
          cpu: "50m"
          memory: "64Mi"
